version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    security_opt:
    - seccomp:unconfined
    restart: always
    environment:
      - MYSQL_DATABASE=bookstore_db
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local